[package]
name = "ludusavi"
version = "0.1.0"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Game save backup tool"
repository = "https://github.com/mtkennerly/ludusavi"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.12.3"
dirs = "3.0.0"
glob = "0.3.0"
iced = "0.1.1"
reqwest = { version = "0.10.6", features = [ "blocking" ] }
serde = { version = "1.0.111", features = ["derive"] }
serde_yaml = "0.8.13"
thiserror = "1.0.20"
walkdir = "2.3.1"
whoami = "0.9.0"
