[package]
name = "ludusavi"
version = "0.3.0"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Game save backup tool"
repository = "https://github.com/mtkennerly/ludusavi"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.12.3"
copypasta = "0.7.0"
dialoguer = "0.6.2"
dirs = "3.0.0"
glob = "0.3.0"
iced = "0.1.1"
iced_native = "0.2.2"
indicatif = { version = "0.15.0", features = ["rayon"] }
itertools = "0.9.0"
rayon = "1.3.1"
reqwest = { version = "0.10.6", features = ["blocking", "rustls-tls"], default-features = false }
serde = { version = "1.0.111", features = ["derive"] }
serde_yaml = "0.8.13"
structopt = "0.3.15"
thiserror = "1.0.20"
walkdir = "2.3.1"
whoami = "0.9.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.7.0"
winapi = { version = "0.3.9", features = ["wincon"], default-features = false }

[profile.dev]
opt-level = 3
